### ISSUE TITLE
SSL issues using the https client against google

### ISSUE THREAD

**Issue by davidrg** [davidrg/ckwin#183]
This seems likely to be a CKW issue (maybe a C-Kermit issue too). OpenSSL version is 1.1.1s. Https works fine with some other hosts so it seems to be specifically an issue with something Google is doing. And if google is doing it, others probably are too.

![image](https://user-images.githubusercontent.com/1887527/233863770-f13a3efe-4a10-4d48-b746-b3f02e50060d.png)

**Comment by jaltman** [comment]
C-Kermit doesn’t support TLS Server Name Indication. It was invented after I left Columbia. Server Name Indicationen.wikipedia.orgOn Apr 23, 2023, at 4:22 PM, David Goodwin ***@***.***) ***@***.***> wrote:﻿
This seems likely to be a CKW issue (maybe a C-Kermit issue too). OpenSSL version is 1.1.1s. Https works fine with some other hosts so it seems to be specifically an issue with something Google is doing. And if google is doing it, others probably are too.

**Comment by davidrg** [comment]
Thanks for that! Turns out to be a pretty simple change for the client to send through the hostname.
