### ISSUE TITLE
why you don't offer a compiled version? 

### ISSUE THREAD

**Issue by Barabba11** [davidrg/ckwin#2]
really a pity, I've an urgency and I don't know how to compile

**Comment by davidrg** [comment]
There is still a fair bit of work to do in this before its generally usable - in particular SSH and a few other features aren't available plus file transfers are currently broken when built with newer compilers.

If you want to give it a go anyway, apparently this build works to an extent: http://ftp2.zx.net.nz/pub/Kermit95/test_builds/3_0-21-nov-2013/winkermit-3.0-test-21-nov-2013-vc6.zip

**Comment by davidrg** [comment]
Downloadable version is now available from the Kermit Project website: https://kermitproject.org/ckw10beta.html
